baseurl: "/website-beta"
exclude: ['.git','.gitignore','Gemfile','Gemfile.lock']
sass:
    style: :compressed
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
